# Generated by Django 5.2.7 on 2025-11-17 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_order_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='table',
            unique_together=set(),
        ),
    ]
