# Generated by Django 5.2.7 on 2025-11-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_table_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='table_number',
            field=models.PositiveIntegerField(),
        ),
    ]
